---

- name: add elastic gpg key
  apt_key: url="https://packages.elastic.co/GPG-KEY-elasticsearch"

- name: add beats repository
  apt_repository: repo="deb https://packages.elastic.co/beats/apt stable main" state=present update_cache=yes

- name: install filebeat
  apt: name=filebeat state=present
  notify:
    - restart filebeat

- name: create filebeat.yml
  template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml
  notify:
    - restart filebeat

- name: flush handlers to prevent start then restart
  meta: flush_handlers

- name: start and enable filebeat
  service: name=filebeat state=started enabled=true
